### ISSUE TITLE
pls supply configure script or release tarball including one.

### ISSUE THREAD

**Issue by rofl0r** [behdad/pangox-compat#1]
thanks for supplying this compat package.
unfortunately due to lack of the configure script, this pulls in an build-time dependency on the highly fragile autoconf/make/libtool environment which i would like to avoid pulling in.
i know that its not nice to have generated files checked into version control,
however in this case it makes sense to have the autoconf-generated files, unless you make a proper release tarball and attach it to a tag.

**Comment by behdad** [comment]
There's release tarballs on gnome ftp IIRC.

**Comment by rofl0r** [comment]
indeed, i found it on http://ftp.gnome.org/pub/GNOME/sources/pangox-compat/0.0/ .
thanks for info.
